insert into Categorii(codC, numeC)
    values (1, 'Carne de pui')

select * from Categorii

insert into Preparate(codP, codC, numeP, pret, timp_preparare)
    values (1, 1, 'Piept de pui file invelit in sunca', 20, 30)
select * from Preparate

insert into Ingrediente(codI, numeI, unitate_masura)
    values (1, 'File din piept de pui', 'file')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (2, 'Ulei de masline', 'lingura')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (3, 'Rozmarin uscat', 'lingurita')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (4, 'Sare', 'lingurita')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (5, 'Paprica', 'lingurita')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (6, 'Sunca cruda', 'felie')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (7, 'Usturoi', 'catel')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (8, 'Ceapa', 'numar')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (9, 'Radacini de telina', 'numar')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (10, 'Morcovi', 'numar')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (11, 'Dovleci mici', 'numar')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (12, 'Pasta de rosii', 'lingura')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (13, 'Vin alb sec', 'mililitru')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (14, 'Coaja de lamaie rasa', 'lingura')
insert into Ingrediente(codI, numeI, unitate_masura)
    values (15, 'Patrunjel tocat', 'lingura')
select * from Ingrediente

insert into Retete(codP, codI, cantitate)
    values (1, 1, 4)
insert into Retete(codP, codI, cantitate)
    values (1, 2, 6)
insert into Retete(codP, codI, cantitate)
    values (1, 3, 1)
insert into Retete(codP, codI, cantitate)
    values (1, 4, 1)
insert into Retete(codP, codI, cantitate)
    values (1, 5, 1)
insert into Retete(codP, codI, cantitate)
    values (1, 6, 8)
insert into Retete(codP, codI, cantitate)
    values (1, 7, 1)
insert into Retete(codP, codI, cantitate)
    values (1, 8, 1)
insert into Retete(codP, codI, cantitate)
    values (1, 9, 3)
insert into Retete(codP, codI, cantitate)
    values (1, 10, 3)
insert into Retete(codP, codI, cantitate)
    values (1, 11, 2)
insert into Retete(codP, codI, cantitate)
    values (1, 12, 1)
insert into Retete(codP, codI, cantitate)
    values (1, 13, 125)
insert into Retete(codP, codI, cantitate)
    values (1, 14, 1)
insert into Retete(codP, codI, cantitate)
    values (1, 15, 1)
select * from Retete
